import Provider from '@/SessionProvider'
import './globals.css'


export const metadata = {
  title: 'Donut Shop',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
     <Provider>
     {children}
     </Provider>
        
      </body>
    </html>
  )
}
